openapi: 3.0.0
info:
  title: "Contoh API documentation"
  description: "Contoh API doc menggunakan OpenAPI/Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: djiwandou@gmail.com
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
paths:
  /greet:
    get:
      tags:
        - greeting
      summary: "Returns a Sample API response"
      description: "A sample greeting to test out the API"
      operationId: greet
      parameters:
        - name: firstname
          in: query
          description: "nama depan"
          required: true
          schema:
            type: string
        - name: lastname
          in: query
          description: "nama belakang"
          required: true
          schema:
            type: string
      responses:
        default:
          description: "successful operation"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
tags:
  - name: greeting
    description: "greet combines first and last name"
paths:
  /users:
    get:
      tags:
        - users
      summary: "Kumpulan data user yang terdaftar"
      description: "Kumpulan data user yang terdaftar"
      operationId: users
      responses:
        default:
          description: "successful operation"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
tags:
  - name: users
    description: "all user"
paths:
  /api/user/id:
    get:
      tags:
        - user-id
      summary: "Detail user berdasarkan ID"
      description: "Detail user berdasarkan ID"
      operationId: user
      parameters:
        - name: id
          in: query
          description: "ID User"
          required: true
          schema:
            type: string
      responses:
        default:
          description: "successful operation"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
tags:
  - name: user
    description: "detail user"
